<a href="https://colab.research.google.com/github/roxcalan/machine-learns/blob/main/ml2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
data= pd.read_csv("/content/Placement_Data_Full_Class.csv")

In [10]:
data

,sl_no,gender,ssc_p,hsc_p,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,M,67.00,91.00,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,2,M,79.33,78.33,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,3,M,65.00,68.00,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,4,M,56.00,52.00,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,5,M,85.80,73.60,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,82.00,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,212,M,58.00,60.00,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,213,M,67.00,67.00,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,214,F,74.00,66.00,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,215,M,62.00,58.00,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [17]:
data['gender']=le.fit_transform(data['gender'])
data['hsc_s']=le.fit_transform(data['hsc_s'])
data['degree_t']=le.fit_transform(data['degree_t'])
data['workex']=le.fit_transform(data['workex'])
data['specialisation']=le.fit_transform(data['specialisation'])

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X=data.drop(columns=['status'])
y=data['status']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

classifier = DecisionTreeClassifier(max_depth=5, criterion='gini')

classifier.fit(X_train, y_train)

y_pred=classifier.predict(X_test)

In [19]:
y_test

200        Placed
212        Placed
138        Placed
176        Placed
15         Placed
111    Not Placed
168    Not Placed
73         Placed
204        Placed
139        Placed
158    Not Placed
30         Placed
186    Not Placed
9      Not Placed
67         Placed
175    Not Placed
171        Placed
18     Not Placed
153        Placed
66         Placed
185        Placed
142        Placed
79     Not Placed
25     Not Placed
104        Placed
145        Placed
189    Not Placed
16         Placed
45     Not Placed
150        Placed
108        Placed
55         Placed
112        Placed
191        Placed
124        Placed
128        Placed
75     Not Placed
135        Placed
118        Placed
98         Placed
96         Placed
183        Placed
117        Placed
93     Not Placed
84         Placed
95         Placed
137        Placed
210        Placed
86         Placed
162        Placed
152        Placed
38         Placed
24         Placed
165    Not Placed
Name: status, dtype: object

In [20]:
y_pred

array(['Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed'],
      dtype=object)

In [21]:
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

In [ ]:
feature_values=[]
for feature_name in X.columns:
  value=input(f"enter value for{feature_name}:")
  feature_values.append(float(value))

predicted_target=classifier.predict([feature_values])
print ('predicted target variable',predicted_target[0])